### ISSUE TITLE
Github Discussions

### ISSUE THREAD

**Issue by indolering** [dafny-lang/rfcs#3]
I came here looking to leave some feedback after trying out Dafny, but the Gitter chat is dead and you apparently shut down the mailing list.  Github has a new [self-contained discussions](https://docs.github.com/en/free-pro-team@latest/github/building-a-strong-community/about-team-discussions) feature, why don't you give that a shot?  Without the ability to at least bounce pre-RFC ideas around, you are unlikely to get much engagement here.

**Comment by robin-aws** [comment]
Just noticed this issue, and I'm happy to say we recently enabled the discussions feature: https://github.com/dafny-lang/dafny/discussions :)
